@baseurl=http://{{$dotenv HOST}}:{{$dotenv PORT}}

@api={{baseurl}}/api/v2

### GET endpoint /
GET {{baseurl}}/ HTTP/1.1

### POST endpoint increment
POST {{api}}/increment HTTP/1.1

### POST endpoint reset-count
POST {{api}}/reset-count HTTP/1.1

### GET endpoint get-count
GET  {{api}}/get-count